version: '3.7'
services:
  web:
    image: nginx:1.17-alpine
    container_name: web
    restart: unless-stopped
    ports:
      - '${APP_PORT}:80'
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - eventnet

  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php
    working_dir: /var/www
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - eventnet
  
networks:
  eventnet:
    driver: bridge